# serverless.yml
service: poc

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  pokemonFunc:
    handler: index.handler
    events:
      - http:
          path: pokemon
          method: get
          cors : true
      - http:
          path: pokemon/id
          method: get
          cors: true
      - http:
          path: pokemon
          method: post
          cors: true
      - http:
          path: pokemon/{id}
          method: put
          cors: true
      - http:
          path: pokemon/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline